### ISSUE TITLE
How does this compare to host bindings?

### ISSUE THREAD

**Issue by Pyrolistical** [torch2424/as-bind#111]
I really don't understand the purpose of as-bind.

Is as-bind solving the same problem as https://www.assemblyscript.org/compiler.html#host-bindings or not? If it is solving the same problem, how does as-bind solve the problem better?

**Comment by MaxGraey** [comment]
`as-bind` was created on top of the loader, back in the era when AssemblyScript didn't support automatically generated host-bindings. Now I would not recommend using as-bind.
