### ISSUE TITLE
Show an example using a function passed into AssemblyScript using the importObject on the README

### ISSUE THREAD

**Issue by torch2424** [torch2424/as-bind#12]
Brought up by @jayphelps in https://github.com/AssemblyScript/meta/issues/19 . Was a bit unclear to them, thus, maybe should make it more prominent. 

Thanks! 😄 👍

**Comment by torch2424** [comment]
Also, @jayphelps, if you don't mind taking a quick look:

Is this what you meant: https://github.com/torch2424/as-bind/blob/master/test/test.js#L185

It's a test that ensures AssemblyScript can call (From within AssemblyScript) a passed JS function, that receives a string passed by AssemblyScript.

**Comment by jayphelps** [comment]
@torch2424 I don't think so.

My questions were about passing and receiving functions (in addition to actual closures) from and to both JS and AS both ways.

So as one example, somehow you could pass a JS function as an argument to an AS exported function.

```ts
/* pseudo code in AssemblyScript */
export function takesAFunction(callback: (str: string) => void): void {
  callback('hello world');
}
```

```ts
/* in JavaScript/TypeScript */
const asyncTask = async () => {
  const instance = await AsBind.instantiate(wasm);
  instance.exports.takesAFunction((str: string) => {
    // as-bind would have had to convert `str` automatically from an AS string to a JS string
    console.log(str.charAt(0)); // some how use the string
  });
};
asyncTask();
```

The opposite eventually would be cool too, passing an AS function as an argument to a JS function that was imported.

Here's some various wasm-bindgen resources:

https://rustwasm.github.io/docs/wasm-bindgen/reference/passing-rust-closures-to-js.html
https://rustwasm.github.io/docs/wasm-bindgen/reference/receiving-js-closures-in-rust.html

**Comment by jayphelps** [comment]
Keep in mind I was merely curious if this interop was supported out of box, for my future reference. At the moment I don't have a blocking requirement on it, as I'm not yet using as-bind.

**Comment by torch2424** [comment]
@jayphelps Ahhh, thanks for expanding on that! Yes, currently that is not supported. So I opened an issue at: https://github.com/torch2424/as-bind/issues/17

Though, I'll keep this issue open with it's original intent, as I still think it'd be good to show an example of this :smile:
