### ISSUE TITLE
Imported JavaScript function always returning NaN

### ISSUE THREAD

**Issue by lastmjs** [torch2424/as-bind#14]
I have an AssemblyScript import that looks like this:

```typescript
export declare function doSomething(): f64;
```

`doSomething` is just a JavaScript function that returns a number. Whenever I use it in AssemblyScript and try to get the value back to JavaScript, it returns NaN.

**Comment by torch2424** [comment]
Ah yes, this is not currently supported, and shown as not supported in the compatibility table on the README.

I told myself if someone opens an issue, I'd look more into how I can support this. But since you opened the issue, I think the time is now haha! 😂 Thank you for this! 😄
