### ISSUE TITLE
import {AsBind} undefined with webpack?

### ISSUE THREAD

**Issue by jfuehner** [torch2424/as-bind#36]
Hi! I'm new to trying to use as-bind with assemblyscript. I followed the [installation instructions](https://github.com/torch2424/as-bind#installation) however when I try and run my javascript I'm receiving `AsBind` as undefined...

I have defined the `import {AsBind} from "as-bind";` within my javascript. Additionally, I have even tried using `const {AsBind} = require("as-bind");` with both producing the same result...

My project is using webpack so its unclear if that has anything to with it. I am using version 0.3.2.

Using this `import asbind from "../node_modules/as-bind/dist/as-bind.esm";` appears to work. I found something similar in the markdown-parser example.

Thanks!

**Comment by torch2424** [comment]
@jfuehner Thank you very much for the issue! 

So did some investigation, and was able to reproduce, this appears to be a debated bug in how webpack handles the "browser" field: https://github.com/webpack/webpack/issues/4674 

I'll go ahead an open a PR to fix this now :smile:

**Comment by torch2424** [comment]
Fixed in `0.3.4` :smile: :+1:
