### ISSUE TITLE
Hello World example appears to return number

### ISSUE THREAD

**Issue by JamesLMilner** [torch2424/as-bind#43]
Hey @torch2424, hope you're good! I was just playing around with the hello world example and noticed it was return an integer instead of a string. 

For example if I compile:

```typescript
export function myExportedFunctionThatTakesAString(value: string): string {
  return "AsBind: " + value;
}
```

Then in Node run: 

```typescript
const { AsBind } = require("as-bind");
const fs = require("fs");
const wasm = fs.readFileSync("./build/optimized.wasm");

(async () => {
  const asBindInstance = await AsBind.instantiate(wasm);

  const result = asBindInstance.exports.myExportedFunctionThatTakesAString("Hello World!");
  console.log("result", result);
})();
```

I'm getting a numeric response like `2944`. Is there a possibility it's returning the memory pointer by any chance? Running latest as-bind and assemblyscript npm modules currently.

I could also be missing something very obvious :sweat_smile:

**Comment by torch2424** [comment]
@JamesLMilner Hello! Oh that's super odd! Yeah that is most likely a memory pointer unfortunately :cry: It looks like you are doing everything right on first glance, I'll do some debugging on my end and see if it's a library issue or not. 

Thanks again for reporting this! :smile:

**Comment by torch2424** [comment]
@JamesLMilner So I tried to reproduce the bug and it doesn't seem to be replicated? https://github.com/torch2424/as-bind/blob/issue-43/test/assembly/test.ts#L14

I know it depends on like how the runtime assigns pointers, but it seems to be working though? :thinking: 

If I may ask, what's your AsBind, AsemblYScript, and AssemblyScript loader version? :smile:

**Comment by JamesLMilner** [comment]
Hi @torch2424 sorry for taking a little while to reply about this.

```
  "dependencies": {
    "@assemblyscript/loader": "^0.14.8",
    "as-bind": "^0.3.6"
  },
  "devDependencies": {
    "assemblyscript": "^0.14.8"
  }
```

**Comment by JamesLMilner** [comment]
[as-bind-bug.zip](https://github.com/torch2424/as-bind/files/5038122/as-bind-bug.zip)

Here's a zip file, you can run `node index.js` and I am seeing a integer log out there.

**Comment by torch2424** [comment]
Thank you for this @JamesLMilner ! :smile: I'll check this out! :smile:

**Comment by torch2424** [comment]
Ah! I found the issue, your build scripts were:

![Screenshot from 2020-08-06 16-00-46](https://user-images.githubusercontent.com/1448289/89591034-04c66f80-d7fe-11ea-91a2-2d6761de54c3.png)

But, you need to add the as-bind entry point to your build script, [it's mentioned in the quick start](https://github.com/torch2424/as-bind#quick-start). I was trying to save some bytes in the library, and just skipping the check, but I think I'll bite the bullet and add them in there to avoid headaches in the future :smile: 

S your build script should be come: 

![Screenshot from 2020-08-06 16-00-46](https://user-images.githubusercontent.com/1448289/89591133-48b97480-d7fe-11ea-8b7e-9083bdedd291.png)

And it works! :smile: 

![Screenshot from 2020-08-06 16-03-10](https://user-images.githubusercontent.com/1448289/89591172-6090f880-d7fe-11ea-898f-42a0665c88b8.png)

**Comment by JamesLMilner** [comment]
@torch2424 ah my bad! Apologies for missing that as it was quite clearly in the documention. Ironically this is the second time I've played around with as-bind so I must have done it the first time and just forgot!

Thanks for taking the time to have a look, appreciate your patience for such a basic issue!

**Comment by torch2424** [comment]
No worries at all @JamesLMilner ! :smile: It's also on me, something I am trying to learn is how to make important things stand out when you skim docs :smile: 

But I'm writing up a quick check now to avoid this for others in the future :smile:
