### ISSUE TITLE
TS7016: Could not find a declaration file for module 'as-bind'

### ISSUE THREAD

**Issue by letmaik** [torch2424/as-bind#49]
I'm trying to use as-bind from typescript but it looks like the location of the typings file in as-bind is non-standard, and there's also no `"types"` field for it in package.json.

```
[!] (plugin typescript) Error: @rollup/plugin-typescript TS7016: Could not find a declaration file for module 'as-bind'. 'C:/.../node_modules/as-bind/dist/as-bind.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/as-bind` if it exists or add a new declaration (.d.ts) file containing `declare module 'as-bind';`
```

**Comment by torch2424** [comment]
Ah! So I wrote Asbind as a normal JS library, so i unfortunately don't have a typings for AsBind :cry: 

If I'm not mistaken, this would would require a rewrite in TypeScript correct? :thinking: Or, we could just throw together a typings on top of the JS library?

**Comment by letmaik** [comment]
You already produce typings, in `dist/as-bind.d.ts`, but they are not referenced in package.json. I think that's the only thing missing!

**Comment by torch2424** [comment]
Ohhhhh! Okay cool I can open a PR for that :smile: I'll do that real quick :smile: :+1:

**Comment by torch2424** [comment]
Released in 0.4.2 :smile:

**Comment by letmaik** [comment]
Just tried it but looks like the types file itself is incorrect :/ Trying to use it you get "AsBind' only refers to a type, but is being used as a value here."

**Comment by torch2424** [comment]
@letmaik Ah. Well, I'm not too familiar with how typings file works, in terms of writing them by hand :hushed: Would you be open to opening a PR for this? :smile: :+1:
