### ISSUE TITLE
lib/as-bind.d.ts doesn't match signature of lib/lib.js

### ISSUE THREAD

**Issue by kevin-lindsay-1** [torch2424/as-bind#52]
Looks like the `.d.ts` only exports an interface, not a constant, and as a result `AsBind` gets the dreaded red squiggly when you try to use it as a value.

**Comment by torch2424** [comment]
Ah! Thanks for opening this issue! :smile: Ah yeah, this was brought up by someone else recently, but I haven't had the chance to update the typings file.

Feel free to open a PR in the meantime, or I can get to it once I get the time :smile: :+1:

**Comment by torch2424** [comment]
Fixed and published in 0.5.0 :smile: 

Unfortunately, I just exported an `any` for now to stop the "red squiggly", but I opened #56 as I think the library should just be written in TypeScript anyways :upside_down_face:
