### ISSUE TITLE
Migration to AS v0.18

### ISSUE THREAD

**Issue by ghalimi** [torch2424/as-bind#60]
Are there any plans to migrate to AssemblyScript v0.18?

Our initial attempts tend to indicate that backward compatibility was lost then.

**Comment by torch2424** [comment]
@ghalimi Hello, thanks for opening this issue! :smile: 

Yes! I was definitely planning on migrating to AS 0.18. I just haven't had the time yet. I'll try and take a look at this in the next day or two! :+1:

**Comment by torch2424** [comment]
Just kidding, opening a PR now and publishing a new version :smile: :tada:

**Comment by Y--** [comment]
Thanks for the quick response @torch2424! Let us know if/how we can help :-)

**Comment by ghalimi** [comment]
@torch2424 You rock!

**Comment by torch2424** [comment]
@Y-- @ghalimi 

Thank you for the kind words haha! :smile: 

I was waiting for travis to run, and then go pulled into a meeting. :upside_down_face: 

But! I just deployed this in `0.6.0`, let me know if it works for y'all! :smile:
