### ISSUE TITLE
Add links to as-loader package

### ISSUE THREAD

**Issue by piotr-oles** [torch2424/as-bind#72]
Hi! 👋🏻
In the last few weeks, I was working on the [as-loader](https://github.com/piotr-oles/as-loader) package (loader for webpack).
It has built-in support for as-bind and has a similar goal to achieve - improve DX with AssemblyScript. I will not advertise the as-loader more, you can read in REAMDE.md what features it provides 😄
Could we add some links in the docs to point other developers to this package?

**Comment by torch2424** [comment]
Oh yeah definitely! I would be super happy to place this on the README! :smile: 

We have a section on the README for projects using as-bind: https://github.com/torch2424/as-bind#projects-using-as-bind So if you could open a PR, I'd be more than happy to merge it in! :smile: 

Thanks!
