### ISSUE TITLE
Make as-bind Assembly Script Entry file a CLI option

### ISSUE THREAD

**Issue by torch2424** [torch2424/as-bind#8]
As mentioned by @jtenner on the slack:

you can instruct users to set as-bind as an entry point so they don't have to explicitly export * from "as-bind"

Put it in the cli options

This is how as2d does it

**Comment by jtenner** [comment]
```
asc entryfile.ts entryfile.ts ...cli options
```

**Comment by jtenner** [comment]
Would you like me to submit a pull request tomorrow?

**Comment by torch2424** [comment]
@jtenner Thanks for the explanation! :smile: 

And I'll go ahead and fix it in a little bit, as I want to launch the library tommorrow :+1: :smile: Thank you for the offer though!
