### ISSUE TITLE
The new version(0.7.0) doesn't work.

### ISSUE THREAD

**Issue by takapiro99** [torch2424/as-bind#81]
First of all, thank you for providing such a great library!

Nice work on the update to @0.7.0.
I realized that default export and some other features has changed.

I tried it on my local environment (Win10, node14, with asc) but it didn't work.
I'll just paste the error message...

```
> asc assembly/index.ts --exportRuntime --transform as-bind --target debug

FAILURE C:\Users\sur6p\OneDrive\Desktop\gr\node_modules\as-bind\dist\transform.cjs.js:1
"use strict";function e(e){if(e&&e.__esModule)return e;var t=Object.create(null);return e&&Object.keys(e).forEach((function(n){if("default"!==n){var r=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(t,n,r.get?r:{enumerable:!0,get:function(){return e[n]}})}})),t.default=e,Object.freeze(t)}var t=e(require("visitor-as/as"));const{CommonFlags:n,NodeKind:r}=t;function i(e){return e.internalName.startsWith("~")}function s(e,t){return 0!=(e.flags&t)}function a(e){var t;return(null===(t=e.getClass())||void 0===t?void 0:t.internalName)??e.toString()}function o(e){let t=e.parent;for(;t!==t.parent;)t=t.parent;return t}function c(e){return{returnType:a(e.signature.returnType),parameters:e.signature.parameterTypes.map((e=>a(e)))}}function u(e){var t;const n={},r=null===(t=e.getClass)||void 0===t?void 0:t.call(e);if(!r)return n;if(n[r.internalName]={id:r.id,byteSize:r.nextMemoryOffset},r.typeArguments)for(const e of r.typeArguments

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.main (C:\Users\sur6p\OneDrive\Desktop\gr\node_modules\assemblyscript\cli\asc.js:520:25)
    at C:\Users\sur6p\OneDrive\Desktop\gr\node_modules\assemblyscript\bin\asc:19:47
```

in the js file, I was just calling as-bind like this;
```
import { instantiate } from "as-bind"; // there was no default export so imported it directly

const fetchAndInstantiateTask = async () => {
  const wasmArrayBuffer = await fetch(wasmModuleUrl).then((response) =>
    response.arrayBuffer()
  );
  return instantiate(wasmArrayBuffer, importObject);
};
const response = await fetchAndInstantiateTask();
return response
```

Since I'm new to the WASM and AS, I have no idea what is going on.. 
I hope this helps. thanks in advance.

**Comment by takapiro99** [comment]
Note: older version(v0.6.1) worked perfectly with me.

**Comment by torch2424** [comment]
Thanks for the issue! :smile: 

cc @surma , what I think might be the issue, is that by default we are suggesting folks use `transform.cjs`, perhaps we should have them just use the direct transform, since I assume it wouldn't inflate code size or anything right? :smile:

**Comment by torch2424** [comment]
Hello @takapiro99 ! I just opened up #83 , which addresses both of the issues you opened. In the process of building this, I tried to do the use case here (Using the transform on node version 14), and it seems to work fine for me?

![Screenshot from 2021-05-27 18-54-55](https://user-images.githubusercontent.com/1448289/119918347-1c9dea00-bf1d-11eb-916b-146c76a3b41c.png)

Also, as @surma mentioned, I think Optional Chaining was added in node 14: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility

So, could you maybe start a fresh project, and seeing if maybe something is going on in your current one? :thinking:

**Comment by takapiro99** [comment]
I was wrong about the WSL environment being mixed up, but with node 14, it worked! Thank you.

**Comment by surma** [comment]
Cool. I’ll close this for now then :) Please re-open if you find there’s something else going wrong.
