### ISSUE TITLE
Does as-bind work with the newest assemblyscript version?

### ISSUE THREAD

**Issue by RehkitzDev** [torch2424/as-bind#86]
When trying to install as-bind I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: issue-85@1.0.0
npm ERR! Found: @assemblyscript/loader@0.19.7
npm ERR! node_modules/@assemblyscript/loader
npm ERR!   @assemblyscript/loader@"^0.19.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @assemblyscript/loader@"0.18.x" from as-bind@0.7.1
npm ERR! node_modules/as-bind
npm ERR!   as-bind@"*" from the root project
```

It seems to look for @assemblyscript/loader@"0.18.x" . The current version is 0.19.7.

Steps to reproduce:

```
npm init
npm install --save-dev assemblyscript
npm install --save as-bind
```

**Comment by torch2424** [comment]
Ah! Thanks for calling this out! Yeah we'll have to update the package.json, if I'm not mistaken 0.18 didn't have a bunch of memory layout changes to 0.19. so I can hopefully merge this in once I cut a release tomorrow with #87 😀🎉

**Comment by torch2424** [comment]
This is now published in: https://github.com/torch2424/as-bind/releases/tag/0.8.0
